# Generated by Django 3.0.6 on 2020-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20200527_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precioCompra',
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVenta',
            field=models.FloatField(default=0),
        ),
    ]
