# Generated by Django 3.0.6 on 2020-05-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20200527_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.FloatField(default=0, null=True),
        ),
    ]
