# Generated by Django 3.0.6 on 2020-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20200527_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0, null=True, verbose_name='existencias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=50, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioCompra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.FloatField(default=0),
        ),
    ]
