# Generated by Django 3.0.6 on 2020-05-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20200527_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioCompra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioVenta',
        ),
    ]
