# Generated by Django 3.0.6 on 2020-05-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20200527_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioCompra',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVenta',
            field=models.FloatField(default=0),
        ),
    ]
