# Generated by Django 3.0.6 on 2020-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10, unique=True, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='genero')),
                ('telefono', models.PositiveIntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('correo', models.EmailField(max_length=254, verbose_name='email')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'unique_together': {('nombre', 'apellido')},
            },
        ),
    ]
