# Generated by Django 3.0.6 on 2020-05-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200527_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
