# Generated by Django 3.0.6 on 2020-05-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precioCompra')),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precioVenta')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='producto.Producto')),
            ],
        ),
    ]
