# Generated by Django 3.0.6 on 2020-05-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20200524_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalCompra',
        ),
        migrations.RenameField(
            model_name='compradetalle',
            old_name='comprobante',
            new_name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='utilidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precioCompra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precioVenta',
            field=models.FloatField(default=0),
        ),
    ]
