# Generated by Django 3.0.6 on 2020-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20200525_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fechaFactura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Factura'),
        ),
        migrations.AddField(
            model_name='compra',
            name='noFactura',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
