# Generated by Django 3.0.6 on 2020-05-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_auto_20200527_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
