# Generated by Django 3.0.6 on 2020-05-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_auto_20200527_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compradetalle',
            name='total',
        ),
    ]
