# Generated by Django 3.0.6 on 2020-05-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
