# Generated by Django 3.0.6 on 2020-05-28 00:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10, unique=True, verbose_name='NIT')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('correo', models.EmailField(max_length=254, verbose_name='email')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'roveedores',
                'db_table': 'proveedor',
            },
        ),
    ]
