# Generated by Django 3.0.6 on 2020-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='nombre'),
        ),
    ]
