# Generated by Django 3.0.6 on 2020-05-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20200527_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
